name: Codecov Action
on: [push, pull_request]
jobs:
    codecov:
        name: Codecov code coverage
        runs-on: ubuntu-latest
        steps:
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
